# Generated by Django 3.0.7 on 2020-08-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashionapp', '0003_auto_20200816_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('image', models.ImageField(default=' ', upload_to='pics')),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
